language: bash

services:
- docker

install:
- git clone --depth 1 git://github.com/machinekit/machinekit.git
- docker pull kinsamanka/mkdocker:wheezy-32
- docker pull kinsamanka/mkdocker:wheezy-64

env:
- TAG=wheezy-32 CMD=build_debs
- TAG=wheezy-32 CMD=run_tests
- TAG=wheezy-64 CMD=build_debs
- TAG=wheezy-64 CMD=run_tests

script:
- docker run --privileged=true 
    -v $(pwd):/opt/rootfs/usr/src -e MK_DIR=${TAG}_${CMD}
    kinsamanka/mkdocker:${TAG} /opt/rootfs/usr/src/${CMD}.sh


