sudo: false
language: bash

services:
- docker

before_install:
- docker pull kinsamanka/mkdocker:wheezy-32
- docker pull kinsamanka/mkdocker:wheezy-64
- docker build -t mk_data .
- docker run -d --name mk_data mk_data


env:
- TAG=wheezy-64    CMD=60
- TAG=wheezy-32    CMD=120

script:
- docker run --privileged=true 
    --volumes-from mk_data
    kinsamanka/mkdocker:${TAG} /bin/sh -xc "ls /data; touch /data/a${TAG}; sleep ${CMD}; touch /data/b${TAG}; ls /data"
