language: bash

services:
- docker

install:
- git clone --depth 1 git://github.com/machinekit/machinekit.git
- docker pull kinsamanka/mkdocker:wheezy-32
- cp run.sh build_mk.sh machinekit 

script:
- docker run --privileged=true 
    kinsamanka/mkdocker:wheezy-32 /usr/src/machinekit/run.sh

