language: bash

services:
- docker

install:
#- git clone --depth 1 git://github.com/machinekit/machinekit.git
- docker pull kinsamanka/testing
#- cp run.sh build_mk.sh machinekit 

script:
- docker run --privileged=true 
    -v $(pwd):/opt/rootfs/usr/src/tmp
    kinsamanka/testing /opt/rootfs/usr/src/tmp/run2.sh

